-- Operational annotation workflow: tasks are immutable source records; annotations retain SOP version.
create table if not exists public.annotation_tasks (
 task_id text primary key, category text not null, query text not null, context text not null,
 model_response text not null, expected_behavior text not null, difficulty text not null,
 source_type text not null default 'synthetic_project_case', created_at timestamptz not null default now()
);
create table if not exists public.annotation_sops (
 sop_id uuid primary key, sop_name text not null, version integer not null check(version > 0),
 status text not null check(status in ('draft','approved','active','retired')),
 content_json jsonb not null, change_summary text not null default '', created_by text not null,
 reviewed_by text, approved_at timestamptz, activated_at timestamptz,
 created_at timestamptz not null default now(), unique(sop_name,version)
);
create unique index if not exists one_active_sop_per_name on public.annotation_sops(sop_name) where status='active';
create table if not exists public.annotation_submissions (
 id uuid primary key, task_id text not null references public.annotation_tasks(task_id),
 annotator_id text not null, sop_id uuid not null references public.annotation_sops(sop_id),
 relevance text not null check(relevance in ('pass','minor_issue','major_issue','not_applicable')),
 correctness text not null check(correctness in ('pass','minor_issue','major_issue','not_applicable')),
 completeness text not null check(completeness in ('pass','minor_issue','major_issue','not_applicable')),
 overall_label text not null check(overall_label in ('accept','revise','reject','escalate')),
 evidence text not null, defect_category text not null default 'none',
 confidence integer not null check(confidence between 1 and 5), handling_seconds integer not null check(handling_seconds >= 0),
 escalated boolean not null default false, is_audit boolean not null default false,
 created_at timestamptz not null default now()
);
create index if not exists annotation_submissions_task_idx on public.annotation_submissions(task_id);
create index if not exists annotation_submissions_created_idx on public.annotation_submissions(created_at desc);
create table if not exists public.annotation_audit_events (
 id bigint generated by default as identity primary key, entity_type text not null, entity_id text not null,
 action text not null, actor text not null, details_json jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);
alter table public.annotation_tasks enable row level security;
alter table public.annotation_sops enable row level security;
alter table public.annotation_submissions enable row level security;
alter table public.annotation_audit_events enable row level security;

-- Seed active SOP v1. This is a project demonstration SOP, not an Amazon SOP.
insert into public.annotation_sops(sop_id,sop_name,version,status,content_json,change_summary,created_by,reviewed_by,approved_at,activated_at)
values ('e04ec5d7-0101-4caa-8d80-000000000001','Seller Response Quality SOP',1,'active',
'{"dimensions":{"relevance":"Does the response address the stated query and requested action?","correctness":"Are claims supported by the supplied context and policy?","completeness":"Does it include the necessary next step or caveat without material omission?"},"labels":{"pass":"Meets the dimension with no material defect","minor_issue":"Limited defect that does not change the main outcome","major_issue":"Materially wrong, unsupported, unsafe, or incomplete"},"overall":{"accept":"No major issues; fit to send","revise":"Fixable issue before sending","reject":"Materially wrong or unsafe response","escalate":"Requires policy, privacy, or specialist decision"},"evidence_required":true,"confidence_scale":"1=low, 5=high"}',
'Initial project SOP; reviewer-approved demonstration baseline.','project-owner','project-reviewer',now(),now())
on conflict (sop_name,version) do nothing;
