-- Run once in the Supabase SQL Editor for the project used by this app.
create table if not exists public.llm_benchmark_runs (
  run_id uuid primary key,
  created_at timestamptz not null default now(),
  status text not null,
  config_json jsonb not null,
  results_json jsonb not null,
  created_by text
);

create table if not exists public.llm_annotations (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.llm_benchmark_runs(run_id) on delete cascade,
  case_id text not null,
  provider text not null,
  model text not null,
  rating integer not null check (rating between 1 and 5),
  label text not null check (label in ('excellent','acceptable','poor','unsafe','needs_review')),
  notes text not null default '',
  reviewer text not null default 'anonymous',
  created_at timestamptz not null default now()
);

create index if not exists idx_llm_runs_created_at on public.llm_benchmark_runs(created_at desc);
create index if not exists idx_llm_annotations_run_id on public.llm_annotations(run_id);
create index if not exists idx_llm_annotations_case on public.llm_annotations(case_id);

-- Backend uses the service-role key, which bypasses RLS. Keep RLS enabled
-- so anon/authenticated clients cannot read benchmark data directly.
alter table public.llm_benchmark_runs enable row level security;
alter table public.llm_annotations enable row level security;
